SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;


CREATE TABLE IF NOT EXISTS `mediaindex` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `path` varchar(255) NOT NULL,
  `unit` varchar(255) NOT NULL,
  `base` varchar(255) NOT NULL,
  `deep` tinyint(2) NOT NULL,
  `type` set('dir','mp3','mp4') NOT NULL,
  `date` datetime NOT NULL,
  `last` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `size` bigint(12) NOT NULL,
  `time` bigint(12) NOT NULL,
  `hook` int(11) NOT NULL DEFAULT '0',
  `hold` int(11) NOT NULL DEFAULT '0',
  `bind` tinyint(1) NOT NULL DEFAULT '0',
  `clip` blob,
  `bugs` longtext NOT NULL,
  `view` longtext NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `path` (`path`),
  KEY `unit` (`unit`),
  KEY `base` (`base`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
